from __future__ import annotations

from pathlib import Path
from typing import Any

from jinja2 import Template


class HTMLReporter:
    """Generate HTML reports for analysis samples using Jinja2."""

    # Embedded template for portability (avoiding external .html files)
    TEMPLATE = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Analysis Report - {{ sample.name }}</title>
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #333; line-height: 1.6; background-color: #f8f9fa; }
            .container { max-width: 1000px; margin: auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
            h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 15px; margin-top: 0; }
            h2 { color: #2980b9; margin-top: 40px; border-left: 5px solid #3498db; padding-left: 15px; }

            .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 30px 0; }
            .stat-card { background: #fdfdfd; padding: 20px; border-radius: 10px; border: 1px solid #e1e4e8; text-align: center; transition: transform 0.2s; }
            .stat-card:hover { transform: translateY(-5px); border-color: #3498db; }
            .stat-value { font-size: 28px; font-weight: bold; color: #27ae60; display: block; }
            .stat-label { font-size: 14px; color: #7f8c8d; text-transform: uppercase; letter-spacing: 1px; }

            table { border-collapse: collapse; width: 100%; margin: 25px 0; border-radius: 8px; overflow: hidden; }
            th, td { border: 1px solid #e1e4e8; padding: 15px; text-align: left; }
            th { background-color: #f2f4f6; color: #2c3e50; font-weight: 600; }
            tr:nth-child(even) { background-color: #fcfcfc; }
            tr:hover { background-color: #f1f7ff; }

            .chart-section { margin-top: 50px; text-align: center; padding: 30px; background: #fff; border: 1px solid #e1e4e8; border-radius: 10px; }
            .footer { margin-top: 60px; font-size: 13px; color: #95a5a6; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }

            .badge { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
            .badge-ctdna { background: #e1f5fe; color: #0288d1; }
            .badge-val { background: #f3e5f5; color: #7b1fa2; }
        </style>
    </head>
    <body>
        <div class="container">
            <div style="display: flex; justify-content: space-between; align-items: baseline;">
                <h1>Analysis Report: {{ sample.name }}</h1>
                <span class="badge {% if sample.sample_type == 'ctdna' %}badge-ctdna{% else %}badge-val{% endif %}">
                    {{ sample.sample_type|upper if sample.sample_type else 'GENERAL' }}
                </span>
            </div>

            <div class="stats-grid">
                <div class="stat-card">
                    <span class="stat-value">{{ sample.results|length }}</span>
                    <span class="stat-label">Tracked Mutations</span>
                </div>
            </div>

            <h2>Patient-Specific Mutations</h2>
            <table>
                <thead>
                    <tr>
                        <th>Mutation Name</th>
                        <th>Total Reads (cons0)</th>
                        <th>Cons Reads (fsize={{ family_size }})</th>
                        <th>VAF (%)</th>
                        <th>MM / mL Plasma</th>
                    </tr>
                </thead>
                <tbody>
                    {% for res in sample.results %}
                    <tr>
                        <td><strong>{{ res.mutation_name }}</strong></td>
                        <td>{{ "{:,}".format(res.total_reads) }}</td>
                        <td>{{ "{:,}".format(res.mm_count) }}</td>
                        <td style="color: {{ '#c0392b' if res.vaf > 0 else '#27ae60' }}; font-weight: bold;">
                            {{ "%.4f"|format(res.vaf) }}%
                        </td>
                        <td>{{ "%.2f"|format(res.mm_per_ml) if res.mm_per_ml is not None else "N/A" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="chart-section">
                <h3>Consensus Reads Distribution</h3>
                <div style="margin-top: 20px;">
                    {{ chart_svg|safe }}
                </div>
            </div>

            <div class="footer">
                Generated by <strong>UMIErrorCorrect2</strong> Analysis Module &bull; {{ date }}
            </div>
        </div>
    </body>
    </html>
    """

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.template = Template(self.TEMPLATE)

    def generate_report(self, sample: Any, family_size: int, output_path: Path) -> None:
        """Render the Jinja2 template and write to output_path."""
        from datetime import datetime

        # Prepare chart data
        names = [r.mutation_name for r in sample.results]
        values = [r.mm_count for r in sample.results]
        chart_svg = self._generate_bar_chart_svg(names, values)

        html_content = self.template.render(
            sample=sample,
            family_size=family_size,
            chart_svg=chart_svg,
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )

        with output_path.open("w") as f:
            f.write(html_content)

    def _generate_bar_chart_svg(self, names: list[str], values: list[int]) -> str:
        """Generate a simple SVG bar chart for inclusion in the report."""
        if not values or all(v == 0 for v in values):
            return "<p style='color: #95a5a6; font-style: italic;'>No mutant molecules detected for tracking.</p>"

        max_val = max(values)
        chart_height = 250
        chart_width = 800
        bar_width = 50
        gap = 30
        left_margin = 60
        bottom_margin = 80
        top_margin = 20

        svg = [
            f'<svg width="{chart_width}" height="{chart_height + bottom_margin + top_margin}" xmlns="http://www.w3.org/2000/svg">'
        ]

        # Draw background lines
        for i in range(5):
            y = top_margin + (chart_height / 4) * i
            val = int(max_val - (max_val / 4) * i)
            svg.append(f'<line x1="{left_margin}" y1="{y}" x2="{chart_width - 20}" y2="{y}" stroke="#eee" />')
            svg.append(
                f'<text x="{left_margin - 10}" y="{y + 5}" font-size="12" text-anchor="end" fill="#95a5a6">{val}</text>'
            )

        for i, (name, val) in enumerate(zip(names, values)):
            h = (val / max_val) * chart_height if max_val > 0 else 0
            x = i * (bar_width + gap) + left_margin + 20
            y = chart_height - h + top_margin

            # Bar
            svg.append(f'<rect x="{x}" y="{y}" width="{bar_width}" height="{h}" fill="#3498db" rx="4">')
            svg.append(f"  <title>{name}: {val}</title>")
            svg.append("</rect>")

            # Label (rotated)
            svg.append(
                f'<text x="{x + bar_width / 2}" y="{chart_height + top_margin + 15}" font-size="11" text-anchor="start" transform="rotate(45, {x + bar_width / 2}, {chart_height + top_margin + 15})" fill="#2c3e50">{name}</text>'
            )

            # Value on top
            if h > 20:
                svg.append(
                    f'<text x="{x + bar_width / 2}" y="{y - 8}" font-size="11" font-weight="bold" text-anchor="middle" fill="#2c3e50">{val}</text>'
                )

        svg.append("</svg>")
        return "\n".join(svg)
